### ISSUE TITLE
Add distance of jumps to --jumps option of count_opcodes script 

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/tools#11]
With the `--jump` option, the number of jumps needing an `EXTENDED_ARG` prefix is tracked, but the distance of the jumps are not.
Categorizing the jumps by distance and target would help us find the best set of jump instructions.

For example, a jump from 500 to 400 is an offset of -100 which could be handled by a hypothetical `JUMP_BACK` instruction.
However, a jump from 800 to 400 would need an extended jump of some form.

By grouping jumps to into `-inf...-256`, `-256...0`, `0...256`, `256...inf` buckets we can see what set of jumps we want.

**Comment by iritkatriel** [comment]
We kinda did this, we group them into abs(delta) < 256 and abs(delta) > 256.

**Comment by markshannon** [comment]
:+1:
