### ISSUE TITLE
Clean up benchmarking portal branches and issues?

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/tools#139]
@ericsnowcurrently Now that we've successfully transitioned to GH Actions for benchmarking, should we just close as "won't fix" all the issues related to the bench tooling, and delete the branches? (There are three pretty stale branches, all yours.)

**Comment by ericsnowcurrently** [comment]
Yeah, I'll clean all that up later today (giving @mdboom a chance to chime in).  Thanks for brining it up.

**Comment by mdboom** [comment]
That makes sense.  If there are any that are still relevant to the new infra (eg. features we haven't got around to in either system), we could move them to `faster-cpython/benchmarking`.

**Comment by mdboom** [comment]
I think this should be done now.  Most were no longer relevant, but I rewrote some that would still be nice to do on the new infra.

There's one remaining issue #3 here that arguably belongs on `ideas` or `cpython`.  I'll leave that for someone else to triage.

**Comment by ericsnowcurrently** [comment]
Thanks for handling the issues.  I've deleted the branches.
