### ISSUE TITLE
[portal] handle ^C in jobs.py attach

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/tools#38]
Currently `KeyboardInterrupt` while `jobs.py attach` is running raises as-is and results in a traceback.  Instead, we could catch it and print a useful message (e.g. "^C (the job is still running in the background)").

**Comment by gvanrossum** [comment]
But it should still exit, right? It's just the traceback that's not useful in this (expected) case.

**Comment by ericsnowcurrently** [comment]
Right, it should still exit.
