### ISSUE TITLE
Some opcode stats are slightly off?

### ISSUE THREAD

**Issue by Fidget-Spinner** [faster-cpython/tools#4]
Currently in the README, the top 20 opcodes for:
PyPI:
```
CALL_METHOD             474,246   4.50%
LOAD_METHOD             474,198   4.50%
```
mypy:
```
CALL_METHOD              10,828   3.61%
LOAD_METHOD              10,823   3.61%
```
This doesn't seem possible. `CALL_METHOD` and `LOAD_METHOD` are [strictly tied](https://docs.python.org/3/library/dis.html#opcode-LOAD_METHOD). ie. their counts should be the same. Yet there is a small difference in the count.

Overall, the error is less than 0.03%, so I think the big picture represented by the stats are accurate. This issue isn't a showstopper, just something interesting I stumbled across.

**Comment by gvanrossum** [comment]
Maybe put an assert in the count script to find where this happens?

**Comment by Fidget-Spinner** [comment]
Yep I plan to eventually work on this if no one else takes it up. I just plopped the issue here so I don't forget.

**Comment by gvanrossum** [comment]
Found it. There's an obscure optimization that seems to copy bits of code. Example:
```py
def f(a):
    a.method(1 if a else 0)
```
The disassembly looks like this:
```
  2           0 LOAD_FAST                0 (a)
              2 LOAD_METHOD              0 (method)
              4 LOAD_FAST                0 (a)
              6 POP_JUMP_IF_FALSE        9 (to 18)
              8 LOAD_CONST               1 (1)
             10 CALL_METHOD              1
             12 POP_TOP
             14 LOAD_CONST               0 (None)
             16 RETURN_VALUE
        >>   18 LOAD_CONST               2 (0)
             20 CALL_METHOD              1
             22 POP_TOP
             24 LOAD_CONST               0 (None)
             26 RETURN_VALUE
```
