### ISSUE TITLE
[portal] Keep CPython builds on the worker in their own location

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/tools#51]
Currently we build CPython on the worker (bench host) for each "compile-bench" request, using a build directory under that request's data directory.  It may be better to instead keep all the builds independent, in a separate directory, to help with re-use.

There are a few things to keep in mind:

* if a build fails, it must be completely cleaned up
* unneeded builds should be cleaned up
   * only keep the most recently used builds?  (delete anything older than some threshold or keep only the N newest)
* we need a way to force a re-build

**Comment by gvanrossum** [comment]
What problem are you trying to solve here? It sounds like your proposed solution might cause more accidental coupling between requests (if re-use happens to hit something nondeterministic in the build process).

**Comment by ericsnowcurrently** [comment]
Yeah, I agree it probably isn't worth doing and may be subject to non-deterministic build conditions.

This was me opening an issue for a note I had jotted down a while back.  IIRC, I was thinking it could help speed jobs up if you wanted to re-run the benchmarks for a specific commit.  In that case it could mostly be an opt-in feature, rather than the default, and doesn't really need the build artifacts to be kept in a separate directory.

We can close this.  If it makes more sense in the future then we can re-open.
