### ISSUE TITLE
[portal] Periodically clean up the worker

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/tools#52]
When a job completes on the worker (bench host), the results files are copied to the corresponding request dir on the portal host.  At the point the data on the worker is mostly no longer needed.  To avoid wasting (limited) disk space, old data needs to be deleted.  However, currently we have no mechanism to clean up jobs after they have finished.

We've already ran out of disk space once.  It would be good if that didn't happen again.  Here are some options:

* continue manually deleting data when we remember or run out of space
* add a new command to do the cleanup, e.g. "jobs.py worker clean [WORKER]"
* at the end of the job, after the results have been copied onto the portal host, ...
    * automatically delete the job's data dir
* set up a cron job to delete (older) requests

Also see [#51](https://github.com/faster-cpython/tools/issues/51).

Note that sometimes it is useful to have access to the CPython build, venv, etc. for later inspection, so we may not want to delete a job's data dir *immediately* after it finishes.

**Comment by gvanrossum** [comment]
How about a cron job that tosses requests older than N days? I'd set N to 14 or 30. You could also toss failed requests sooner (there seem to be a bunch of historical requests that never completed.)

**Comment by ericsnowcurrently** [comment]
+1 to both your suggestions.  The simple approach is all we need here.

**Comment by mdboom** [comment]
This is less of an issue with the new infrastructure, which doesn't retain build products (which are much larger than results files).  Still, I filed https://github.com/faster-cpython/benchmarking/issues/72 to track disk usage issues in the new infrastructure (which is not on fire, but could be someday).
