### ISSUE TITLE
[portal] Supporting editing an existing request

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/tools#54]
Being able to edit an existing request could be useful, e.g. if it was just copied (see [#53](https://github.com/faster-cpython/tools/issues/53)).  A command for this could help with that.  (The alternative is editing the request.json, etc. by hand, which is probably fine for now.)

Note that this is only practical for requests that were just created and have not been queued up yet or canceled.

**Comment by gvanrossum** [comment]
This seems just weird. What's the use case? Why not cancel it and submit a fixed request?

**Comment by ericsnowcurrently** [comment]
Agreed.  This was based on a short note I'd left myself a while back, which I figured I'd record here.  I haven't actually needed something like this a single time, more or less.
