### ISSUE TITLE
[portal] Move the benchmark tooling to pyperformance?

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/tools#56]
The benchmark tooling is fairly tightly coupled to pyperformance.  It certainly lives in the same space.  So it may make sense to move everything in PORTAL/ to pyperformance.

This would involve:

1. update pyperformance to expose API (classes, functions, etc.) for its domain to replace various things implemented in PORTAL/jobs/*.py
   * some of it may belong in pyperf rather than pyperformance
2. update the code under PORTAL/ to use those
3. move everything under PORTAL/ to pyperformance, next to the top-level "pyperformance" directory (not under it)

This move would reduce maintenance costs of the tool by getting rid of duplicated functionality between the two code bases.  Living in the pyperformance repo also means that there is a larger group of potential maintainers.

Furthremore, the move would expose the tooling to a wider audience, which aligns with the assumption that it will be helpful to the Python community.

**Comment by gvanrossum** [comment]
I'm not sure that's a good idea. By the same token, pyperformance should be part of the pyperf repo. ;-)

If you want a larger audience, this repo is public and there's nothing to stop you from publicizing it more (e.g. see if Pablo is interested, since he also runs a pyperformance server -- two even, for speed.python.org). Or maybe you could make a new repo here.

**Comment by ericsnowcurrently** [comment]
Yeah, the best course isn't particularly clear, in large part because there probably isn't a need to change anything. 😄  Doing anything about this is pretty low priority and not really worth much consideration for now.

**Comment by mdboom** [comment]
We probably won't do this *specific* thing, but there is an issue in a similar vein (making our infrastructure easier for others to use) here: https://github.com/faster-cpython/ideas/issues/531
