### ISSUE TITLE
[portal] Report "main" as "3.x.0a0"

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/tools#65]
"main" can get out of date.  There's an existing convention to solve this in the CPython code: call it alpha 0 of the next major release.  (For version branches, it is the last release tag followed by a "+".)

* [x] add support in `_utils.Version`
* [ ] update `_utils.GitRef`, etc.
* [ ] update request metadata
* [ ] update "list" command
* [ ] update "show" command

(Thanks to @gvanrossum for suggesting doing this.)

**Comment by mdboom** [comment]
This is kinda/sorta implemented in the GH Actions version -- we always include both a commit hash and the "Python version", which would be something like `3.12.0a4+` on main.
