### ISSUE TITLE
Benchmarking: Queue Waiting Jobs

### ISSUE THREAD

**Issue by brandtbucher** [faster-cpython/tools#7]
(Follows from my discussion with @ericsnowcurrently earlier today.)

Currently, our benchmark runner will reject new jobs if one is already running. If it's not too difficult, we should try to set up a queueing mechanism, so that we can schedule two or more runs at once.

**Comment by ericsnowcurrently** [comment]
https://github.com/faster-cpython/tools/pull/18

**Comment by ericsnowcurrently** [comment]
We can work on other changes separately.
