### ISSUE TITLE
[portal] Verify/Fix Geometric Means for Pyston Benchmarks Results

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/tools#72]
As of #69, we are recording the geometric mean for the various benchmark results.  This can be seen at https://github.com/faster-cpython/ideas/blob/main/README.md.  The means for the pyston benchmarks are identical to those of the pyperformance benchmarks, which is suspicious.  We need to verify and, if wrong, fix those values.

**Comment by mdboom** [comment]
Yeah, though those are incorrect -- all of the results files contain all of the benchmarks from both suites.  There is likely in the bug that separates the results out by suite.  I've been working through that but haven't been able to reproduce it locally -- somehow the bug only happens in the cronjob.
