### ISSUE TITLE
Benchmarking: Don't Require A Live Connection

### ISSUE THREAD

**Issue by brandtbucher** [faster-cpython/tools#8]
(Follows from my discussion with @ericsnowcurrently earlier today.)

Currently, our benchmark runner will fail if the submitting user's SSH connection closes for any reason. If it's not too difficult, we should try to gracefully handle dropped connections and continue running the user's current job.

**Comment by mdboom** [comment]
Maybe there's someway `screen` or `tmux` could be helpful here.

**Comment by ericsnowcurrently** [comment]
Yeah, I considered that (and that's what I do personally).  However, if we're adding a job queue (#8) then we'll need to be able to run jobs in the background, which requires this feature.  'tmux' won't help as much with that.

**Comment by ericsnowcurrently** [comment]
Implemented in #17.
