### ISSUE TITLE
Devise a way to manage SSH authorized keys on all workers

### ISSUE THREAD

**Issue by mdboom** [faster-cpython/tools#84]
When I set up the Mac worker, I just copied the `authorized_keys` file from the Linux worker to the Mac.

1. I'm not sure how @ericsnowcurrently set that up in the first place and if there's any automation to managing users already in place.
2. We probably want some way to keep this in sync so we don't have to update things in multiple places as we add/remove users (short of implementing LDAP).

**Comment by ericsnowcurrently** [comment]
> I'm not sure how @ericsnowcurrently set that up in the first place

Pretty sure I just did it by hand.  I may have some notes (or a simple script somewhere though, if it's important.

**Comment by mdboom** [comment]
Not important, just didn't want to redo any work if it existed.

I think the sweet spot is (a) manually edit the file for new people, (b) a script to automatically sync to all workers.  Automating (a) is probably not worth the effort.
