### ISSUE TITLE
Benchmarking: CPU Isolation

### ISSUE THREAD

**Issue by brandtbucher** [faster-cpython/tools#9]
(Follows from my discussion with @ericsnowcurrently earlier today.)

Unfortunately, our benchmarking system appears to be somewhat inconsistent from run to run. For example, running the full suite for the same exact `main` commit (`2d21612f0dd8`) on two different days reports a statistically significant speedup of 1% (with per-benchmark results ranging from -6% to +9%): 

<details>

```
Slower (15):
- scimark_sparse_mat_mult: 4.95 ms +- 0.16 ms -> 5.23 ms +- 0.19 ms: 1.06x slower
- unpickle_list: 4.78 us +- 0.07 us -> 4.89 us +- 0.05 us: 1.02x slower
- pidigits: 188 ms +- 0 ms -> 192 ms +- 0 ms: 1.02x slower
- scimark_fft: 358 ms +- 7 ms -> 365 ms +- 4 ms: 1.02x slower
- scimark_lu: 149 ms +- 4 ms -> 151 ms +- 6 ms: 1.02x slower
- scimark_sor: 159 ms +- 1 ms -> 162 ms +- 2 ms: 1.02x slower
- pyflate: 541 ms +- 5 ms -> 549 ms +- 5 ms: 1.01x slower
- chameleon: 7.56 ms +- 0.08 ms -> 7.66 ms +- 0.07 ms: 1.01x slower
- nbody: 123 ms +- 2 ms -> 124 ms +- 2 ms: 1.01x slower
- sqlalchemy_imperative: 18.6 ms +- 0.1 ms -> 18.8 ms +- 0.2 ms: 1.01x slower
- go: 175 ms +- 2 ms -> 176 ms +- 2 ms: 1.01x slower
- raytrace: 350 ms +- 2 ms -> 353 ms +- 3 ms: 1.01x slower
- dulwich_log: 68.9 ms +- 0.5 ms -> 69.3 ms +- 0.5 ms: 1.01x slower
- logging_simple: 6.72 us +- 0.08 us -> 6.74 us +- 0.06 us: 1.00x slower
- fannkuch: 425 ms +- 4 ms -> 426 ms +- 2 ms: 1.00x slower

Faster (23):
- regex_v8: 25.5 ms +- 0.2 ms -> 23.4 ms +- 0.4 ms: 1.09x faster
- regex_effbot: 3.31 ms +- 0.06 ms -> 3.09 ms +- 0.05 ms: 1.07x faster
- regex_dna: 223 ms +- 1 ms -> 208 ms +- 1 ms: 1.07x faster
- pickle_dict: 29.5 us +- 0.2 us -> 27.6 us +- 0.2 us: 1.07x faster
- unpack_sequence: 46.0 ns +- 0.5 ns -> 43.7 ns +- 1.2 ns: 1.05x faster
- telco: 6.42 ms +- 0.12 ms -> 6.24 ms +- 0.17 ms: 1.03x faster
- unpickle: 13.8 us +- 0.1 us -> 13.4 us +- 0.2 us: 1.03x faster
- spectral_norm: 119 ms +- 3 ms -> 116 ms +- 1 ms: 1.03x faster
- mako: 12.7 ms +- 0.1 ms -> 12.4 ms +- 0.1 ms: 1.03x faster
- json_dumps: 12.8 ms +- 0.1 ms -> 12.5 ms +- 0.1 ms: 1.02x faster
- xml_etree_generate: 84.7 ms +- 1.0 ms -> 82.9 ms +- 0.8 ms: 1.02x faster
- pickle: 10.2 us +- 0.1 us -> 9.95 us +- 0.07 us: 1.02x faster
- float: 86.9 ms +- 0.9 ms -> 85.6 ms +- 1.6 ms: 1.02x faster
- pickle_list: 4.64 us +- 0.06 us -> 4.58 us +- 0.06 us: 1.01x faster
- crypto_pyaes: 90.8 ms +- 1.0 ms -> 89.9 ms +- 0.9 ms: 1.01x faster
- meteor_contest: 107 ms +- 0 ms -> 106 ms +- 0 ms: 1.01x faster
- deltablue: 5.29 ms +- 0.05 ms -> 5.25 ms +- 0.05 ms: 1.01x faster
- json_loads: 28.0 us +- 0.3 us -> 27.9 us +- 0.2 us: 1.01x faster
- hexiom: 7.78 ms +- 0.07 ms -> 7.74 ms +- 0.08 ms: 1.00x faster
- pathlib: 19.2 ms +- 0.3 ms -> 19.1 ms +- 0.2 ms: 1.00x faster
- xml_etree_iterparse: 107 ms +- 1 ms -> 106 ms +- 1 ms: 1.00x faster
- xml_etree_process: 61.2 ms +- 0.7 ms -> 60.9 ms +- 0.8 ms: 1.00x faster
- sympy_expand: 512 ms +- 3 ms -> 510 ms +- 5 ms: 1.00x faster

Benchmark hidden because not significant (20): 2to3, chaos, django_template, logging_format, logging_silent, nqueens, pickle_pure_python, python_startup, python_startup_no_site, regex_compile, richards, scimark_monte_carlo, sqlalchemy_declarative, sqlite_synth, sympy_integrate, sympy_sum, sympy_str, tornado_http, unpickle_pure_python, xml_etree_parse

Geometric mean: 1.01x faster
```
</details>

I think that the single most effective change we can make is to configure the system with the [`isolcpus` and `rcu_nocbs` GRUB command-line options](https://pyperf.readthedocs.io/en/latest/system.html). I've done this on my own machines before, and immediately noticed significantly better stability and reproducibility. Perhaps @pablogsal can weigh in here, too?

(We also skip the `pyperf system tune` step when benchmarking, since the entire system is already living in a "tuned" state. For peace-of-mind, though, I would favor enabling this quick step in the generated config file for all benchmarking runs, so that we don't end up running benchmarks on an un-tuned system in the event of a reboot, and the generated `config.ini` file accurately represents the run.)

**Comment by pablogsal** [comment]
Yeah, CPU isolation and deactivating kernel interrupts in the isolated CPUs is a must. I always configure the configuration file to run "system tune" as well in any case just as a precaution. In all my systems this has reduced the noise considerably and specially it isolates the benchmarks from anything else running on the machine, which I think is very important to get reproducible results.

**Comment by brandtbucher** [comment]
I've only ever personally isolated a single CPU, since it's always been on machines meant for other work or personal use.

For a dedicated benchmarking machine, how many of the CPUs would you recommend isolating? One? Half? All but one?

**Comment by brandtbucher** [comment]
Were `pyperformance` or `pyperf` updated as part of that switchover? That could be a big part of the difference, if so.

**Comment by pablogsal** [comment]
> > You need to isolate at least the virtual CPUs that are in the same physical core. You can check the configuration on your system with `lscpu --extended`.
> 
> Yeah, got that, but does the actual number of isolated physical cores matter, or is one sufficient for running one `pyperformance` run at a time? It seems like one would be fine to me, but I might be missing something. 

I don't think we have any benchmark running multiple threads but in all my systems I had at least 2 physical CPUs isolated if that helps.

**Comment by gvanrossum** [comment]
I'd be curious to know how we can do this on Windows, but @zooba can help us with that once we have a dedicated machine somewhere.

**Comment by brandtbucher** [comment]
I don’t think I’ve found a way to do it on macOS, either. CPU affinity (which I think `pyperf` tries to do through `psutil`) gets you part of the way there, though.
