### ISSUE TITLE
run-bench fails (can't connect to GitHub)

### ISSUE THREAD

**Issue by iritkatriel** [faster-cpython/tools#94]
Am I doing something wrong? Has something changed?

```
iritkatriel@pyperf-portal:~$ ping github.com
ping: github.com: Temporary failure in name resolution
iritkatriel@pyperf-portal:~$ bench BENCH/jobs.py run-bench --benchmarks='-flaskblogging' --remote origin main
fatal: unable to access 'https://github.com/faster-cpython/ideas/': Could not resolve host: github.com
```

**Comment by ericsnowcurrently** [comment]
Running `systemd-resolve --status` shows no nameservers set.  (Normally it would have a "DNS Servers" entry.)  Other files indicate similar.

I suspect something happened with the DHCP client on the portal host.  It looks like there is no DHCP lease right now.  There is some indication in the logs that something happened recently:

```
$ journalctl | grep -Ei 'dhcp'
...
Aug 30 06:40:52 pyperf-portal python3[8563]: 2022-08-30T06:40:52.304657Z INFO EnvHandler ExtHandler EnvMonitor: Detected dhcp client restart. Restoring routing table.
```

I'm looking at verifying the status of the DHCP client and restarting if necessary.

**Comment by ericsnowcurrently** [comment]
I reset the DHCP lease and things look good again.

What I did:

```
$ sudo dhclient -v -r eth0
$ sudo dhclient -v eth0
```

@iritkatriel, feel free to confirm and close this issue.  Thanks!

**Comment by iritkatriel** [comment]
Confirmed! Thank you.
